Config = {}
Config.Locale = GetConvar("esx:locale", "pt")

Config.OxInventory = GetResourceState("ox_inventory") ~= 'missing'

Config.Accounts = {
    bank = {
        label = TranslateCap("account_bank"),
        round = true,
    },
    black_money = {
        label = TranslateCap("account_black_money"),
        round = true,
    },
    money = {
        label = TranslateCap("account_money"),
        round = true,
    },
}

Config.StartingAccountMoney = { bank = 250000 }

Config.StartingInventoryItems = false -- table/false

Config.DefaultSpawns = { -- If you want to have more spawn positions and select them randomly uncomment commented code or add more locations
    { x = 163.1694, y = -986.6396, z = 30.0919, heading =  155.6283},
    --{x = 224.9865, y = -865.0871, z = 30.2922, heading = 1.0},
    --{x = 227.8436, y = -866.0400, z = 30.2922, heading = 1.0},
    --{x = 230.6051, y = -867.1450, z = 30.2922, heading = 1.0},
    --{x = 233.5459, y = -868.2626, z = 30.2922, heading = 1.0}
}

Config.AdminGroups = {
    ["superadmin"] = true,
    ["admin"] = true,
    ["mod"] = true,
}

Config.EnablePaycheck = true -- enable paycheck
Config.LogPaycheck = true -- Logs paychecks to a nominated Discord channel via webhook (default is false)
Config.EnableSocietyPayouts = false -- pay from the society account that the player is employed at? Requirement: esx_society
Config.MaxWeight = 24 -- the max inventory weight without a backpack
Config.PaycheckInterval = 7 * 60000 -- how often to receive paychecks in milliseconds
Config.EnableDebug = false -- Use Debug options?
Config.EnableDefaultInventory = false -- Display the default Inventory ( F2 )
Config.EnableWantedLevel = false -- Use Normal GTA wanted Level?
Config.EnablePVP = true -- Allow Player to player combat

Config.Multichar = GetResourceState("esx_multicharacter") ~= "missing"
Config.Identity = true -- Select a character identity data before they have loaded in (this happens by default with multichar)
Config.DistanceGive = 3.0 -- Max distance when giving items, weapons etc.

Config.AdminLogging = true -- Logs the usage of certain commands by those with group.admin ace permissions (default is false)

Config.DisableHealthRegeneration = false -- Player will no longer regenerate health
Config.DisableVehicleRewards = true -- Disables Player Receiving weapons from vehicles
Config.DisableNPCDrops = true -- stops NPCs from dropping weapons on death
Config.DisableDispatchServices = true -- Disable Dispatch services
Config.DisableScenarios = false -- Disable Scenarios
Config.DisableWeaponWheel = false -- Disables default weapon wheel
Config.DisableAimAssist = true -- disables AIM assist (mainly on controllers)
Config.DisableVehicleSeatShuff = true -- Disables vehicle seat shuff
Config.DisableDisplayAmmo = false -- Disable ammunition display
Config.RemoveHudComponents = {
    [1] = true, --WANTED_STARS,
    [2] = false, --WEAPON_ICON
    [3] = false, --CASH
    [4] = false, --MP_CASH
    [5] = false, --MP_MESSAGE
    [6] = true, --VEHICLE_NAME
    [7] = true, -- AREA_NAME
    [8] = true, -- VEHICLE_CLASS
    [9] = true, --STREET_NAME
    [10] = false, --HELP_TEXT
    [11] = false, --FLOATING_HELP_TEXT_1
    [12] = false, --FLOATING_HELP_TEXT_2
    [13] = false, --CASH_CHANGE
    [14] = false, --RETICLE
    [15] = false, --SUBTITLE_TEXT
    [16] = false, --RADIO_STATIONS
    [17] = false, --SAVING_GAME,
    [18] = false, --GAME_STREAM
    [19] = false, --WEAPON_WHEEL
    [20] = false, --WEAPON_WHEEL_STATS
    [21] = false, --HUD_COMPONENTS
    [22] = false, --HUD_WEAPONS
}

Config.SpawnVehMaxUpgrades = false -- admin vehicles spawn with max vehicle settings
Config.CustomAIPlates = "........" -- Custom plates for AI vehicles
-- Pattern string format
--1 will lead to a random number from 0-9.
--A will lead to a random letter from A-Z.
-- . will lead to a random letter or number, with a 50% probability of being either.
--^1 will lead to a literal 1 being emitted.
--^A will lead to a literal A being emitted.
--Any other character will lead to said character being emitted.
-- A string shorter than 8 characters will be padded on the right.

pedList = { 
    's_m_y_clown_01',
    's_f_y_hooker_01',
    's_f_y_hooker_02',
    's_f_y_hooker_03',
    'u_m_y_abner',
    'a_m_o_acult_02',
    's_f_y_airhostess_01',
    'u_m_m_aldinapoli',
    'csb_anita',
    'csb_anton',
    'u_m_y_antonb',
    'g_m_m_armboss_01',
    'g_m_m_armgoon_01',
    'g_m_y_armgoon_02',
    's_m_m_autoshop_01',
    'g_m_y_azteca_01',
    'u_m_y_babyd',
    'g_m_y_ballaeast_01',
    'g_m_y_ballaorig_01',
    'g_m_y_ballasout_01',
    'u_m_m_bankman',
    's_m_y_barman_01',
    's_f_m_fembarber',
    'u_m_y_baygor',
    's_f_y_baywatch_01',
    's_m_y_baywatch_01',
    'a_f_m_beach_01',
    'a_f_y_beach_01',
    'a_m_m_beach_01',
    'a_m_m_beach_02',
    'a_m_o_beach_01',
    'a_m_y_beach_01',
    'a_m_y_beach_02',
    'a_m_y_beach_03',
    'a_m_y_beachvesp_01',
    'a_m_y_beachvesp_02',
    'a_f_m_bevhills_01',
    'a_f_m_bevhills_02',
    'a_f_y_bevhills_01',
    'a_f_y_bevhills_02',
    'a_f_y_bevhills_03',
    'a_f_y_bevhills_04',
    'a_m_m_bevhills_01',
    'a_m_m_bevhills_02',
    'a_m_y_bevhills_01',
    'a_m_y_bevhills_02',
    'u_m_m_bikehire_01',
    'u_f_y_bikerchic',
    'a_f_m_bodybuild_01',
    's_m_m_bouncer_01',
    'a_m_y_breakdance_01',
    's_m_y_busboy_01',
    'a_m_y_busicas_01',
    'a_f_m_business_02',
    'a_f_y_business_01',
    'a_f_y_business_02',
    'a_f_y_business_03',
    'a_f_y_business_04',
    'a_m_m_business_01',
    'a_m_y_business_01',
    'a_m_y_business_02',
    'a_m_y_business_03',
    's_m_o_busker_01',
    'csb_car3guy1',
    'csb_car3guy2',
    'g_m_m_chigoon_01',
    'g_m_m_chigoon_02',
    'csb_chin_goon',
    'u_m_y_chip',
    'csb_cletus',
    's_m_m_cntrybar_01',
    'u_f_y_comjane',
    'csb_customer',
    'a_m_y_cyclist_01',
    'u_m_y_cyclist_01',
    's_m_y_dealer_01',
    'csb_denise_friend',
    's_m_y_devinsec_01',
    'a_m_y_dhill_01',
    's_m_y_doorman_01',
    'a_f_m_downtown_01',
    'a_m_y_downtown_01',
    'a_f_m_eastsa_01',
    'a_f_m_eastsa_02',
    'a_f_y_eastsa_01',
    'a_f_y_eastsa_02',
    'a_f_y_eastsa_03',
    'a_m_m_eastsa_01',
    'a_m_m_eastsa_02',
    'a_m_y_eastsa_01',
    'a_m_y_eastsa_02',
    'a_f_y_epsilon_01',
    'a_m_y_epsilon_01',
    'a_m_y_epsilon_02',
    'g_m_y_famca_01',
    'g_m_y_famdnf_01',
    'g_m_y_famfor_01',
    'g_f_y_families_01',
    'a_m_m_farmer_01',
    'a_f_m_fatbla_01',
    'a_m_m_fatlatin_01',
    'a_f_m_fatwhite_01',
    'u_m_m_fibarchitect',
    'u_m_y_fibmugger_01',
    'u_m_m_filmdirector',
    'u_m_o_finguru_01',
    'a_f_y_fitness_01',
    'a_f_y_fitness_02',
    'csb_fos_rep',
    'csb_g',
    's_m_m_gaffer_01',
    'csb_ramp_gang',
    'a_m_y_gay_01',
    'a_m_y_gay_02',
    'a_m_m_genfat_01',
    'a_m_m_genfat_02',
    'a_f_y_genhot_01',
    'a_f_o_genstreet_01',
    'a_m_o_genstreet_01',
    'a_m_y_genstreet_01',
    'a_m_y_genstreet_02',
    'u_m_m_glenstank_01',
    'a_f_y_golfer_01',
    'a_m_m_golfer_01',
    'a_m_y_golfer_01',
    'u_m_m_griff_01',
    'csb_grove_str_dlr',
    'u_m_y_guido_01',
    'u_m_y_gunvend_01',
    's_m_m_hairdress_01',
    'csb_hao',
    'a_m_m_hasjew_01',
    'a_m_y_hasjew_01',
    'csb_ramp_hic',
    's_m_m_highsec_01',
    's_m_m_highsec_02',
    'a_f_y_hiker_01',
    'a_m_y_hiker_01',
    'a_m_m_hillbilly_01',
    'a_m_m_hillbilly_02',
    'a_f_y_hippie_01',
    'u_m_y_hippie_01',
    'a_m_y_hippy_01',
    'a_f_y_hipster_01',
    'a_f_y_hipster_02',
    'a_f_y_hipster_03',
    'a_f_y_hipster_04',
    'a_m_y_hipster_01',
    'a_m_y_hipster_02',
    'a_m_y_hipster_03',
    'csb_ramp_hipster',
    'u_f_y_hotposh_01',
    'csb_hugh',
    'csb_imran',
    'a_f_o_indian_01',
    'a_f_y_indian_01',
    'a_m_m_indian_01',
    'a_m_y_indian_01',
    'csb_janitor',
    's_m_m_janitor',
    'u_m_m_jesus_01',
    'a_m_y_jetski_01',
    'u_f_y_jewelass_01',
    'u_m_m_jewelsec_01',
    'u_m_m_jewelthief',
    'a_f_y_juggalo_01',
    'a_m_y_juggalo_01',
    'g_m_m_korboss_01',
    'g_m_y_korean_01',
    'g_m_y_korean_02',
    'g_m_y_korlieut_01',
    'a_f_m_ktown_01',
    'a_f_m_ktown_02',
    'a_f_o_ktown_01',
    'a_m_m_ktown_01',
    'a_m_o_ktown_01',
    'a_m_y_ktown_01',
    'a_m_y_ktown_02',
    's_m_m_lathandy_01',
    'a_m_y_latino_01',
    's_m_m_lifeinvad_01',
    's_m_m_linecook',
    'g_m_y_lost_01',
    'g_m_y_lost_02',
    's_f_m_maid_01',
    'a_m_m_malibu_01',
    'u_m_y_mani',
    's_m_m_mariachi_01',
    'u_m_m_markfost',
    'csb_maude',
    'a_m_y_methhead_01',
    'csb_ramp_mex',
    'g_m_m_mexboss_01',
    'g_m_m_mexboss_02',
    'a_m_m_mexcntry_01',
    'g_m_y_mexgang_01',
    'g_m_y_mexgoon_02',
    'g_m_y_mexgoon_03',
    'a_m_m_mexlabor_01',
    'a_m_y_mexthug_01',
    's_f_y_migrant_01',
    's_m_m_migrant_01',
    'u_m_y_militarybum',
    's_m_y_mime',
    'u_f_m_miranda',
    'u_f_y_mistress',
    'a_m_y_motox_01',
    'a_m_y_motox_02',
    'u_f_o_moviestar',
    's_f_y_movprem_01',
    's_m_m_movprem_01',
    'a_m_y_musclbeac_01',
    'a_m_y_musclbeac_02',
    'a_m_m_afriamer_01',
    'a_m_m_og_boss_01',
    'csb_ortega',
    'csb_oscar',
    'a_m_m_paparazzi_01',
    'u_m_y_paparazzi',
    'u_m_y_party_01',
    'u_m_m_partytarget',
    'g_m_y_pologoon_01',
    'g_m_y_pologoon_02',
    'a_m_m_polynesian_01',
    'a_m_y_polynesian_01',
    'u_f_y_poppymich',
    'csb_porndudes',
    's_m_m_postal_01',
    's_m_m_postal_02',
    'u_f_y_princess',
    'a_f_m_prolhost_01',
    'u_f_o_prolhost_01',
    'csb_prologuedriver',
    'u_f_m_promourn_01',
    'u_m_m_promourn_01',
    'csb_reporter',
    'u_m_m_rivalpap',
    'a_m_y_roadcyc_01',
    's_m_y_robber_01',
    'csb_roccopelosi',
    'a_f_y_runner_01',
    'a_m_y_runner_01',
    'a_m_y_runner_02',
    'a_f_y_rurmeth_01',
    'a_m_m_rurmeth_01',
    'a_f_m_salton_01',
    'a_f_o_salton_01',
    'a_m_m_salton_01',
    'a_m_m_salton_02',
    'a_m_m_salton_03',
    'a_m_m_salton_04',
    'a_m_o_salton_01',
    'a_m_y_salton_01',
    'g_m_y_salvaboss_01',
    'g_m_y_salvagoon_01',
    'g_m_y_salvagoon_02',
    'g_m_y_salvagoon_03',
    'u_m_y_sbike',
    'a_f_y_scdressy_01',
    'csb_screen_writer',
    's_f_m_shop_high',
    's_f_y_shop_low',
    's_m_y_shop_mask',
    's_f_y_shop_mid',
    'a_f_y_skater_01',
    'a_m_m_skater_01',
    'a_m_y_skater_01',
    'a_m_y_skater_02',
    'a_f_m_skidrow_01',
    'a_m_m_skidrow_01',
    'a_m_m_socenlat_01',
    'a_f_m_soucent_01',
    'a_f_m_soucent_02',
    'a_f_o_soucent_01',
    'a_f_o_soucent_02',
    'a_f_y_soucent_01',
    'a_f_y_soucent_02',
    'a_f_y_soucent_03',
    'a_m_m_soucent_01',
    'a_m_m_soucent_02',
    'a_m_m_soucent_03',
    'a_m_m_soucent_04',
    'a_m_o_soucent_01',
    'a_m_o_soucent_02',
    'a_m_o_soucent_03',
    'a_m_y_soucent_01',
    'a_m_y_soucent_02',
    'a_m_y_soucent_03',
    'a_m_y_soucent_04',
    'a_f_m_soucentmc_01',
    'u_m_m_spyactor',
    'u_f_y_spyactress',
    'a_m_y_stbla_01',
    'a_m_y_stbla_02',
    'a_m_m_stlat_02',
    'a_m_y_stlat_01',
    's_m_m_strpreach_01',
    'g_m_y_strpunk_01',
    'g_m_y_strpunk_02',
    's_m_m_strvend_01',
    's_m_y_strvend_01',
    'a_m_y_stwhi_01',
    'a_m_y_stwhi_02',
    'a_m_y_sunbathe_01',
    'a_m_y_surfer_01',
    's_f_m_sweatshop_01',
    's_f_y_sweatshop_01',
    'u_m_o_taphillbilly',
    'u_m_y_tattoo_01',
    'a_f_y_tennis_01',
    'a_m_m_tennis_01',
    'csb_tonya',
    'a_f_m_tourist_01',
    'a_f_y_tourist_01',
    'a_f_y_tourist_02',
    'a_m_m_tourist_01',
    'a_f_m_tramp_01',
    'a_m_m_tramp_01',
    'a_m_o_tramp_01',
    'u_m_o_tramp_01',
    'a_f_m_trampbeac_01',
    'a_m_m_trampbeac_01',
    'a_m_m_tranvest_01',
    'a_m_m_tranvest_02',
    's_m_m_trucker_01',
    'g_f_y_vagos_01',
    's_m_y_valet_01',
    'a_m_y_vindouche_01',
    'a_f_y_vinewood_01',
    'a_f_y_vinewood_02',
    'a_f_y_vinewood_03',
    'a_f_y_vinewood_04',
    'a_m_y_vinewood_01',
    'a_m_y_vinewood_02',
    'a_m_y_vinewood_03',
    'a_m_y_vinewood_04',
    's_m_y_waiter_01',
    'u_m_m_willyfist',
    'a_f_y_yoga_01',
    'a_m_y_yoga_01',
    'csb_agent',
    'csb_mp_agent14',
    'u_m_m_edtoh',
    'a_f_y_femaleagent',
    'csb_jackhowitzer',
    'csb_money',
    'csb_paige',
    'csb_popov',
    'csb_undercover',
    'csb_vagspeak',
    's_m_y_xmech_02_mp',
    'g_f_importexport_01',
    'g_m_importexport_01',
    'u_m_y_smugmech_01'
}

Config.Logs = {
    color = '16753920',
    username = '📜 Logs Vanguard',
    avatar = 'https://i.imgur.com/RfAKyVy.png',
  
    communtiyName = '📜 Logs Vanguard',
    communtiyLogo = 'https://i.imgur.com/RfAKyVy.png',
  
    footerText = 'Sistema de Logs',
    footerIcon = 'https://imgur.com/kUv3lFo.png',
  }